apiVersion : apps/v1
kind: Deployment
metadata:
  name: aravindcogdenversample 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aravindcogdenversample
  template:
    metadata:
      labels:
        app: aravindcogdenversample 
    spec:
      containers:
        - name: aravindcogdenversample 
          image: denvertestregistry.azurecr.io/aravindcogdenversample
          imagePullPolicy: Always
          ports:
          - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
    name: aravindcogdenversample
    labels: 
      run: aravindcogdenversample
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: aravindcogdenversample
    loadBalancerIP: 20.69.72.46
